(add-load-path ".." :relative)
(load "bootstrap.scm")
(select-module covers)
(print (multirember-y 'tuna '(shrimp salad tuna salad and tuna)))
; (shrimp salad salad and)
(print (multirember 'pie '(apple custard pie linzer pie torte)))
; (apple custard linzer torte)
(print (multirember-dash 'pie '(apple custard pie linzer pie torte)))
; (apple custard linzer torte)
(print ((multirember-f-old eq?) 'blue '(red blue yellow blue)))
; (red yellow)
(print ((multirember-f eq?) 'blue '(red blue yellow blue)))
; (red yellow)
