(add-load-path ".." :relative)
(load "bootstrap.scm")
(select-module covers)
(print (union-old '(tomatoes and macaroni casserole) '(macaroni and cheese)))
; (tomatoes casserole macaroni and cheese)
(print (union-a '(tomatoes and macaroni casserole) '(macaroni and cheese)))
; (tomatoes casserole macaroni and cheese)
(print (union-b '(tomatoes and macaroni casserole) '(macaroni and cheese)))
; (tomatoes casserole macaroni and cheese)
(print (union '(tomatoes and macaroni casserole) '(macaroni and cheese)))
; (tomatoes casserole macaroni and cheese)
