(load "../bootstrap.scm")
(select-module misc)
(print (atom? 'Harry))
(print (atom? '()))
(print (atom? '(car (cdr '(swing low sweet cherry oat)))))
(print (atom? (car (cdr '(swing low sweet cherry oat)))))
