(add-load-path ".." :relative)
(load "bootstrap.scm")
(select-module values)
(print (meaning '(cons z x) '(((x y)
                               ((a b c) (d e f)))
                              ((u v w)
                               (1 2 3))
                              ((x y z)
                               (4 5 6)))))
; (6 a b c)
