(add-load-path ".." :relative)
(load "bootstrap.scm")
(select-module stars)
(print (rember 'mint '(lamd chops and mint jelly)))
; (lamd chops and jelly)
(print (rember 'mint '(lamb chops and mint flavored mint jelly)))
; (lamb chops and flavored mint jelly)
