(add-load-path ".." :relative)
(load "bootstrap.scm")
(select-module bangs)
(print Rs)
; ()
(print Ns)
; ()
(print (deepR 3))
; (((pizza)))
(print Rs)
; ((((pizza))))
(print Ns)
; (3)
(print (deepR 5))
; (((((pizza)))))
(print Rs)
; ((((((pizza))))) (((pizza))))
(print Ns)
; (5 3)
(print (deepR 3))
; (((pizza)))
(print Rs)
; ((((pizza))) (((((pizza))))) (((pizza))))
(print Ns)
; (3 5 3)
