(add-load-path ".." :relative)
(load "bootstrap.scm")
(select-module bangs)
(deepR 3)
(deepR 5)
(deepR 3)
(print (deepM-a 3))
; (((pizza)))
(print (deepM-a 6))
; ((((((pizza))))))
(print (deepM-b 6))
; ((((((pizza))))))
(print (deepM-c 6))
; ((((((pizza))))))
(print (deepM-d 6))
; ((((((pizza))))))
(print (deepM-d 16))
; ((((((((((((((((pizza))))))))))))))))
(print (deepM-e 16))
; ((((((((((((((((pizza))))))))))))))))
(print (deepM-f 16))
; ((((((((((((((((pizza))))))))))))))))
