(add-load-path ".." :relative)
(load "bootstrap.scm")
(select-module bangs)
(print "ingredients: " ingredients)
; ingredients: ()
(print (sweet-toothR 'chocolate))
; (chocolate cake)
(print "ingredients: " ingredients)
; ingredients: (chocolate)
(print (sweet-toothR 'fruit))
; (fruit cake)
(print "ingredients: " ingredients)
; ingredients: (fruit chocolate)
(print (sweet-toothR 'cheese))
; (cheese cake)
(print "ingredients: " ingredients)
; ingredients: (cheese fruit chocolate)
(print (sweet-toothR 'carot))
; (carot cake)
(print "ingredients: " ingredients)
; ingredients: (carot cheese fruit chocolate)
