(add-load-path ".." :relative)
(load "bootstrap.scm")
(select-module skips)
(print (intersect-old '(tomatoes and macaroni) '(macaroni and cheese)))
; (and macaroni)
(print (intersect-a '(tomatoes and macaroni) '(macaroni and cheese)))
; (and macaroni)
(print (intersectall-old '((3 mangos and) (3 kiwis and) (3 hamburgers))))
; (3) 
(print (intersectall-a '((3 mangos and) (3 kiwis and) (3 hamburgers))))
; (3) 
(print (intersectall-b '((3 mangos and) (3 kiwis and) (3 hamburgers))))
; (3) 
(print (intersectall '((3 mangos and) (3 kiwis and) (3 hamburgers))))
; (3) 
