(add-load-path ".." :relative)
(load "bootstrap.scm")
(select-module skips)
(print (rember-beyond-first 'roots '(noodles spaghetti spatzle bean-thread roots potatoes yam others rice)))
; (noodles spaghetti spatzle bean-thread)
