(add-load-path "lib" :relative)
(load "toys.scm")
(load "agains.scm")
(load "conses.scm")
(load "nums.scm")
(load "stars.scm")
(load "shadows.scm")
(load "relations.scm")
(load "lambda.scm")
(load "againandagains.scm")
