(add-load-path ".." :relative)
(load "bootstrap.scm")
(select-module changesames)
(set-kounter 0)
(define dozen (lotsC 12))
(print (kounter))
(set-kounter 0)
(define bakers-dozen (add-at-end dozen))
(print (kounter))
(set-kounter 0)
(define bakers-dozen-too (add-at-end-tooC dozen))
(print (kounter))
(set-kounter 0)

